apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vdt-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/theWorstSolution/vdt-be-helmChart.git
    targetRevision: HEAD
    path: .
    # - repoURL: https://github.com/theWorstSolution/vdt-fe-helmChart.git
    #   targetRevision: main
    #   chart: vdt-fe-chart
    #   helm:
    #     valueFiles:
    #       - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
