apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vdt-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  sources:
    - repoURL: https://github.com/theWorstSolution/vdt-be-helmChart.git
      targetRevision: HEAD
      chart: vdt-be-chart
      helm:
        valueFiles:
          - values.yaml
    # - repoURL: https://github.com/theWorstSolution/vdt-fe-helmChart.git
    #   targetRevision: HEAD
    #   chart: vdt-fe-chart
    #   helm:
    #     valueFiles:
    #       - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
