apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port   2020
        Flush        5
        Log_Level    debug
        Daemon       off
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/*.log
        Parser      docker
        Tag         kube.*

    [OUTPUT]
        Name        es
        Match       *
        Host        116.103.226.146
        Port        9200
        Index       thanhnc_0325640405
        Type        _doc
        HTTP_User   elastic
        HTTP_Passwd iRsUoyhqW-CyyGdwk6V_
        tls         Off

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
