apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port   2020
        Flush        5
        Log_Level    info
        Daemon       off

    [INPUT]
        Name        tail
        Path        /var/log/nginx/access.log,/var/log/nginx/error.log
        Parser      nginx
        Tag         nginx.*

    [INPUT]
        Name        tail
        Path        /var/log/express/error.log,/var/log/express/combined.log
        Parser      json
        Tag         express.*

    [OUTPUT]
        Name        es
        Match       *
        Host        116.103.226.146
        Port        9200
        Index       thanhnc_0325640405
        Type        _doc
        HTTP_User   elastic
        HTTP_Passwd iRsUoyhqW-CyyGdwk6V_

  parsers.conf: |
    [PARSER]
        Name        nginx
        Format      regex
        Regex       ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>[^ ]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)" "(?<http_x_forwarded_for>[^"]*)$
        Time_Key    time_local
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
