apiVersion: v1
kind: Secret
metadata:
  name: haproxy-cert
type: Opaque
stringData:
  fullchain.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC0gz6thXCHCumO
    Hyeo/vwpI+/fC7OqLasUShiQruWrA5prEsqNZDe+d+u+ApS80+HdYIfS6Q5fa9dp
    4CPRMj6OOPdVyeWZVAco7lk77mMDx5m8gPDZ1YsY9mfqsOpqjOpFLZql6zotjd3I
    1DoJl+/TKlVtMTmVy15rejVJ5LnQAF/55acByeqdt/+Q0+GFD1xyQ9fwcbglNWzg
    XJ4BMLvLo0xQOnt7xfAe/noVxGhOyhK1ufHh+0elwaYLQRcoCkpjPhtvsHYQF4e5
    oZ4EUlJEQygiC4mW0bd0U4qiFacIToeoksUU8+BtnO+OrnpLBdplGWT91o2oKVsI
    z9/FtWMZAgMBAAECgf8zUoskE96zqwsqJmhXJCgf03NNdz0dygLH1ElMR0kp1jfa
    XiHvo6ERKuLJfqk5BrvVkK7ENjXNoluu9WanSrQQu7Pf5yvgWfFmDTm/dPVowkUF
    01oU3kabwAVd66XfEzGIVROQz9BfR+RG2ccUPFVzfYODLLKOGzH0E7ilN3UKwEwt
    rUcjVSwSbyzehKk7Aguv88xOfuM81C24sFLwGbdAMGAHLMSVngarf4V02kdUVsnE
    ffG2I8qR6AFzgKPBiD9/rgfk5olUtDoG882Ns52jGkAjxBXTJyVM1O2gpy+OlI1l
    LESIgyVtTQ1TO7K/4ejvnRUr6g9ChzZeo3rX5ssCgYEAvXX+VF5WNtizf/CzDk8f
    NUf3SeSeZEPW9q4xmgSG7KH0cXjs3wfzGD2LqtwpdrZsiktLJDd+n3ojSjHFLYZE
    d6ZCuo1rgLxO/jRA8wSD773zQrcqt5kJn47C9NbTYf2qAWccg79l7lZrfluEwe9x
    jSKE5T9lyDfZA32QUa9qUcMCgYEA8+i8Q/b5BH9N/e4U6TKUfSbJ9+gfhQ3UFErA
    lkIENnAcMsLHKz32YUviLxokivTny99F3McVJErUW5jj2ibSHn/vt8ynbpwLaY5L
    aKecC+qJkinAoC4vMzHECYBbzDduIFgIplsaAF97IBzOMQHb19JzRXYZCKhHpYhB
    VyHDrfMCgYBdkGDab4AqM9hpjYgPv/lMic7Q2itynqIRTrNGOYgcYlrikvJ/rmBa
    D0LjTTjY3Hw7y7U/HHzW6y10XaHfupgjcqMvl9mISPbFyS5uFUPG6MqyntxksRo0
    hv82hMT9dpU3fiFx2trO2jTZwP6N+97a8ToqMKXmO9ZbR+42uOdLmwKBgBGS6U20
    U8jhK0tqhhMvU8eYreCw1uSNVISJxkqNQyRw+3ck1ZjmBASKpSdjqNJiRvlHgw8f
    QQS2Z4qZ/4DOX0FXUnxZwI6Vq7TVTdWijfnF0le3rmtcKIZ1xXwxxWt3avXloenq
    knsIZiSwLqMVUTPBtBCDK9aV2WOx55NRmXnFAoGBALv7BweeThyaGlWO0kiBRY9K
    +yoB+dHURQ9k6N83/lpDUpTjyTBuiMUMLmdLt51/Gz4ad4T5bOX7PyS6xfPFN2Pk
    4tMhmFZiyQts0+bKokaBuusb1OXzmUAqTpQTgI9UItE9deVWGgD3KDWHop4g9zF2
    +oTgexmSNepAVyG3jee8
    -----END PRIVATE KEY-----
    -----BEGIN CERTIFICATE-----
    MIIDATCCAekCFC8sXUztl7sSDmwv8QmU7TME+QyNMA0GCSqGSIb3DQEBCwUAMD0x
    CzAJBgNVBAYTAlZOMQswCQYDVQQIDAJITjEhMB8GA1UECgwYSW50ZXJuZXQgV2lk
    Z2l0cyBQdHkgTHRkMB4XDTI0MDYxMjIwNTQyMloXDTI1MDYxMjIwNTQyMlowPTEL
    MAkGA1UEBhMCVk4xCzAJBgNVBAgMAkhOMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRn
    aXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0gz6t
    hXCHCumOHyeo/vwpI+/fC7OqLasUShiQruWrA5prEsqNZDe+d+u+ApS80+HdYIfS
    6Q5fa9dp4CPRMj6OOPdVyeWZVAco7lk77mMDx5m8gPDZ1YsY9mfqsOpqjOpFLZql
    6zotjd3I1DoJl+/TKlVtMTmVy15rejVJ5LnQAF/55acByeqdt/+Q0+GFD1xyQ9fw
    cbglNWzgXJ4BMLvLo0xQOnt7xfAe/noVxGhOyhK1ufHh+0elwaYLQRcoCkpjPhtv
    sHYQF4e5oZ4EUlJEQygiC4mW0bd0U4qiFacIToeoksUU8+BtnO+OrnpLBdplGWT9
    1o2oKVsIz9/FtWMZAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAC5I2kEnNRZquhvV
    qyqRO/dqf4xnSYAXjNB79EAmsmemZU/NstFyijJiSQ7Y9M6Ak1Jpl3XA8UCZw8mQ
    FWR6KmuMscqM41I8t5JKWZU5R8Zm3qOnncrIR0bulPgDdmZOTSoCKzCE9W2k+jDi
    hywDQIrL5ANl89SylNT9aZX+uPD99ZwXN2DA00Yu64ikaWa1bvUnKPkE3uOSOYhX
    4FB04gjPvaBTQW6rjjQNO9Os9X74iNzXBIji8J42B2zGKUmN6DgBHKNEmN/0HkJ6
    CS7qDrROPARqBPaHD+jefovwzHkMGJA/T7kroj2KQDwcSnNqLOFGStfmPQl2CZC8
    z9Vg8Yo=
    -----END CERTIFICATE-----

