apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      name: mongodb
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: mongodb
