apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      port: 27017
    replication:
      replSetName: rs0
