apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mongodb-storage-class/pv-1  # Path on the node
  storageClassName: mongodb-storage-class
