apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # Base64 encoded 'mongoadmin'
  mongo-root-password: c2VjdXJlcGFzc3dvcmQ=  # Base64 encoded 'securepassword'
