apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vdt-app
  labels:
    app: vdt
spec:
  selector:
    matchLabels:
      name: cadvisor
  podMetricsEndpoints:
  - port: http-metrics