apiVersion: v1
kind: Service
metadata:
  name: prometheus-fe-exporter
  labels:
    app: vdt
spec:
  selector:
    app: vdt
  ports:
    - name: port
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: ClusterIP
